CREATE DATABASE retail_store;
USE retail_store;

 -- Customers Table
CREATE TABLE customers (
    customer_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    city VARCHAR(30)
);


 -- Stores Table
CREATE TABLE stores (
    store_id INT PRIMARY KEY AUTO_INCREMENT,
    store_name VARCHAR(50) NOT NULL,
    location VARCHAR(50)
);

 -- Products Table
CREATE TABLE products (
    product_id INT PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(50) NOT NULL,
    category VARCHAR(30),
    price DECIMAL(10,2)
);

 -- Orders Table
CREATE TABLE orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_id INT,
    store_id INT,
    product_id INT,
    quantity INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (store_id) REFERENCES stores(store_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

 -- Customers
INSERT INTO customers (customer_name, email, city) VALUES
('John Smith', 'john@example.com', 'Lagos'),
('Alice Johnson', 'alice@example.com', 'Abuja'),
('Michael Brown', 'michael@example.com', 'Lagos'),
('Sarah Williams', 'sarah@example.com', 'Port Harcourt'),
('David Lee', 'david@example.com', 'Abuja'),
('Grace Adams', 'grace@example.com', 'Ibadan');

select * from customers;

 -- Stores
INSERT INTO stores (store_name, location) VALUES
('Tech World', 'Lagos'),
('Gadget Hub', 'Abuja'),
('Everyday Essentials', 'Ibadan'),
('Mega Electronics', 'Port Harcourt');

select * from stores;

 -- Products
INSERT INTO products (product_name, category, price) VALUES
('Laptop', 'Electronics', 250000),
('Smartphone', 'Electronics', 150000),
('Headphones', 'Accessories', 30000),
('Microwave', 'Appliances', 80000),
('Desk Chair', 'Furniture', 60000),
('Notebook', 'Stationery', 1000);

select * from Products;

 -- Orders
 INSERT INTO orders (customer_id, store_id, product_id, quantity, order_date) VALUES
(1, 1, 1, 1, '2023-06-01'),
(1, 1, 3, 2, '2023-06-05'),
(2, 2, 2, 1, '2023-06-07'),
(3, 1, 1, 1, '2023-06-10'),
(3, 4, 4, 1, '2023-06-12'),
(4, 4, 2, 1, '2023-06-15'),
(5, 2, 5, 2, '2023-06-20'),
(6, 3, 6, 5, '2023-06-25'),
(2, 2, 3, 1, '2023-06-28'),
(1, 1, 2, 1, '2023-07-01');

select * from Orders;

 -- 1. Customers with their City and E-mail
 select * from customers;
 
  -- 2. All orders with the customer name, product nmae, and store name
  select o.order_id,
  c.customer_name,
  p.product_name,
  s.store_name
  from orders o
  inner join customers c on o.customer_id = c.customer_id
  inner join products p on o.product_id = p.product_id
  inner join stores s on o.store_id = s.store_id;
  
  -- 3. All customers including those who have not made any order
   select o.order_id,
  c.customer_name
   from orders o
  left join customers c on o.customer_id = c.customer_id;
  
  -- 4. All products including those who never ordered
 select o.order_id,
  p.product_name
   from orders o
  right join products p on p.product_id = p.product_id;
 
 -- 5. Total revenue generated by each store
 select s.store_name, sum(p.price * o.quantity) as Total_revenue
 from orders o
  inner join stores s on o.store_id = s.store_id
  inner join products p on o.product_id = p.product_id
 group by s.store_name;
 
  -- 6. Total number of products sold by category
  select p.category, sum(o.quantity) as Total_Products_Sold
  from orders o
  left join products p on o.product_id = p.product_id
 group by p.category
 order by sum(o.quantity)desc;
 
  -- 7. Customers with more than two orders
  select c.customer_id, c.customer_name, count(order_id) as Orders
   from orders o
  inner join customers c on o.customer_id = c.customer_id
  group by c.customer_id
  having count(order_id)>2;
  
 -- 8. Top 3 Customers who spent the most
 select c.customer_id, c.customer_name, sum(o.quantity * p.price) as Total_spent
   from orders o
  inner join customers c on o.customer_id = c.customer_id
   inner join products p on o.product_id = p.product_id
  group by c.customer_id
  order by sum(o.quantity * p.price) desc limit 3;
  
  -- 9. Most Expensive Product Purchased
select distinct product_name, price
from products
where price = (
select max(price) as Most_Expensive_Product from products p
inner join orders o on p.product_id = o.product_id
);

 -- 10. Customers who bought a laptop
 select customer_name
 from customers
 where customer_id in (
 select customer_id from orders
 where product_id in(select product_id from products
 where product_name = 'Laptop')
 );